/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Nitish' at '25/2/21 11:50 AM' with Gradle 2.14-rc-2
 *
 * @author Nitish, @date 25/2/21 11:50 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main(String[] args) {
    	System.out.println("heyyy");
    }
}
